#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=main.py
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=output/slurm_output_%A.out

module purge
module load 2023
module load CUDA/12.4.0
module load Anaconda3/2023.07-2

# Setup
cd $HOME/ai4mi_project
git submodule init
git submodule update

# Environment
source activate ai4mi

# Run main.py
python -O main.py --dataset SEGTHOR_CLEAN --mode full --epoch 25 --dest ./results --gpu